#!/bin/bash

# request-review.sh - Generate a structured code review request
# Usage: ./request-review.sh --branch <branch-name> --reviewer <reviewer-name>

set -e

# Default values
BRANCH=""
REVIEWER=""
OUTPUT_FORMAT="markdown"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --branch)
            BRANCH="$2"
            shift 2
            ;;
        --reviewer)
            REVIEWER="$2"
            shift 2
            ;;
        --format)
            OUTPUT_FORMAT="$2"
            shift 2
            ;;
        --help)
            echo "Usage: $0 --branch <branch-name> --reviewer <reviewer-name> [--format markdown|json]"
            echo ""
            echo "Options:"
            echo "  --branch    Branch name to review (required)"
            echo "  --reviewer  Reviewer name or email (optional)"
            echo "  --format    Output format: markdown (default) or json"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Validate required arguments
if [[ -z "$BRANCH" ]]; then
    echo "Error: --branch is required"
    exit 1
fi

# Check if we're in a git repository
if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    echo "Error: Not a git repository"
    exit 1
fi

# Get current branch if not specified
CURRENT_BRANCH=$(git branch --show-current)
BASE_BRANCH="main"

# If branch is not specified, use current branch
if [[ -z "$BRANCH" ]]; then
    BRANCH="$CURRENT_BRANCH"
fi

# Find common ancestor
MERGE_BASE=$(git merge-base "$BASE_BRANCH" "$BRANCH" 2>/dev/null || echo "")

if [[ -z "$MERGE_BASE" ]]; then
    echo "Warning: Could not find common ancestor with $BASE_BRANCH"
    MERGE_BASE=$(git rev-parse HEAD~10)
fi

# Get changed files
CHANGED_FILES=$(git diff --name-only "$MERGE_BASE" "$BRANCH")
FILE_COUNT=$(echo "$CHANGED_FILES" | grep -c . || echo "0")

# Get diff stats
DIFF_STATS=$(git diff --stat "$MERGE_BASE" "$BRANCH")

# Get commit messages
COMMITS=$(git log --oneline "$MERGE_BASE".."$BRANCH")

# Generate review request
generate_markdown() {
    cat << EOF
# Code Review Request

## 📋 Overview

**Branch:** \`$BRANCH\`
**Base Branch:** \`$BASE_BRANCH\`
**Files Changed:** $FILE_COUNT
EOF

    if [[ -n "$REVIEWER" ]]; then
        echo "**Reviewer:** $REVIEWER"
    fi

    cat << EOF

## 📝 Summary of Changes

$DIFF_STATS

## 🔄 Commits in this Branch

\`\`\`
$COMMITS
\`\`\`

## 📂 Changed Files

$CHANGED_FILES

## ✅ Review Checklist

Please review the following aspects:

### Functionality
- [ ] Does the code do what it's supposed to do?
- [ ] Are edge cases handled correctly?
- [ ] Are error cases properly managed?

### Code Quality
- [ ] Is the code readable and well-organized?
- [ ] Are variable and function names clear?
- [ ] Is there unnecessary complexity?

### Testing
- [ ] Are there sufficient tests?
- [ ] Do tests cover the new functionality?
- [ ] Are test cases meaningful?

### Security & Performance
- [ ] Are there any security concerns?
- [ ] Is the code performant?
- [ ] Are there potential memory leaks?

### Documentation
- [ ] Is the code properly documented?
- [ ] Are complex logic sections explained?
- [ ] Is the API documentation updated?

## 🎯 Key Areas to Review

EOF

    # Analyze file types and suggest review focus
    if echo "$CHANGED_FILES" | grep -q "\.test\." || echo "$CHANGED_FILES" | grep -q "\.spec\."; then
        echo "- **Tests:** Changes include test files - verify test coverage and quality"
    fi

    if echo "$CHANGED_FILES" | grep -q "package.json\|requirements.txt\|Cargo.toml"; then
        echo "- **Dependencies:** Dependency changes detected - review for security and necessity"
    fi

    if echo "$CHANGED_FILES" | grep -q "\.env\|config\."; then
        echo "- **Configuration:** Config changes detected - check for sensitive data"
    fi

    if echo "$CHANGED_FILES" | grep -q "schema\|migration"; then
        echo "- **Database:** Schema or migration changes - verify data integrity"
    fi

    cat << EOF

## 💬 Comments

<!-- Add any specific concerns or questions for the reviewer -->

## 🔗 Links

- Branch: \`$BRANCH\`
- Compare: [View Full Diff](link-to-compare)

---
*Generated by code-review-suite on $(date)*
EOF
}

# Output based on format
case "$OUTPUT_FORMAT" in
    markdown)
        generate_markdown
        ;;
    json)
        echo "{"
        echo "  \"branch\": \"$BRANCH\","
        echo "  \"baseBranch\": \"$BASE_BRANCH\","
        echo "  \"reviewer\": \"$REVIEWER\","
        echo "  \"fileCount\": $FILE_COUNT,"
        echo "  \"changedFiles\": ["
        echo "$CHANGED_FILES" | sed 's/^/    "/;s/$/",/' | sed '$ s/,$//'
        echo "  ],"
        echo "  \"commits\": ["
        echo "$COMMITS" | sed 's/^/    "/;s/$/",/' | sed '$ s/,$//'
        echo "  ]"
        echo "}"
        ;;
    *)
        echo "Unknown format: $OUTPUT_FORMAT"
        exit 1
        ;;
esac